---
- name: Install Prometheus and Grafana
  hosts: monitoring
  become: yes

  vars:
    prometheus_version: "2.48.0"
    grafana_version: "10.0.0"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    # ------------------------
    # Install Prometheus
    # ------------------------
    - name: Create prometheus user
      user:
        name: prometheus
        shell: /bin/false

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move Prometheus binaries
      command: mv /opt/prometheus-{{ prometheus_version }}.linux-amd64 /opt/prometheus

    - name: Create Prometheus service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

    # ------------------------
    # Install Grafana
    # ------------------------
    - name: Install dependencies for Grafana
      apt:
        name: apt-transport-https
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana
      apt:
        name: grafana={{ grafana_version }}
        state: present

    - name: Enable and start Grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started
