---
- name: Install Docker, Git and deploy Yawiz web application
  hosts: all
  become: yes

  vars:
    docker_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
    docker_repo_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    app_name: "yawiz-web"
    app_dest: "/opt/yawiz"

  tasks:
    - name: Update APT and install dependencies
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: "{{ docker_repo_key_url }}"
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Create application directory
      file:
        path: "{{ app_dest }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy application files
      copy:
        src: "{{ item }}"
        dest: "{{ app_dest }}/"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      with_items:
        - Dockerfile
        - index.html
        - style.css
        - script.js

    - name: Stop existing container
      docker_container:
        name: "{{ app_name }}"
        state: absent
      ignore_errors: yes

    - name: Remove existing image
      docker_image:
        name: "{{ app_name }}"
        state: absent
      ignore_errors: yes

    - name: Build Docker image
      docker_image:
        name: "{{ app_name }}"
        build:
          path: "{{ app_dest }}"
        source: build
        state: present

    - name: Run Docker container
      docker_container:
        name: "{{ app_name }}"
        image: "{{ app_name }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"

    - name: Wait for application to be ready
      wait_for:
        port: 80
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60

    - name: Show running containers
      command: docker ps
      register: docker_ps
      changed_when: false

    - name: Display deployment status
      debug:
        msg: "✅ Application deployed successfully on {{ inventory_hostname }} at http://{{ ansible_default_ipv4.address }}"